apiVersion: v1
kind: Namespace
metadata:
  name: bugstracker-production
  labels:
    name: bugstracker-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: bugstracker-staging
  labels:
    name: bugstracker-staging
    environment: staging
